### ISSUE TITLE
make all failed

### ISSUE THREAD

**Issue by ziang87** [pulp-platform/pulp#20] opened 2019-12-25 07:36 UTC
Hello.When I  build the SDK with this command:make all.And an error occured.I don‘t know how to solve it.Please help!

root@cp1-VirtualBox:/home/cp1/pulp-sdk# make all
git submodule update --init
source init.sh && ./pulp-tools/bin/plpbuild --p sdk checkout build env --stdout
Configuring Pulp project at /home/cp1/pulp-sdk
Traceback (most recent call last):
  File "./pulp-tools/bin/plpbuild", line 3, in <module>
    import plptools as plp
  File "/home/cp1/pulp-sdk/pulp-tools/bin/plptools.py", line 27, in <module>
    from plpobjects import *
  File "/home/cp1/pulp-sdk/pulp-tools/bin/plpobjects.py", line 32, in <module>
    from openpyxl import Workbook
  File "/usr/local/lib/python3.5/dist-packages/openpyxl/__init__.py", line 6, in <module>
    from openpyxl.workbook import Workbook
  File "/usr/local/lib/python3.5/dist-packages/openpyxl/workbook/__init__.py", line 4, in <module>
    from .workbook import Workbook
  File "/usr/local/lib/python3.5/dist-packages/openpyxl/workbook/workbook.py", line 7, in <module>
    from openpyxl.worksheet.worksheet import Worksheet
  File "/usr/local/lib/python3.5/dist-packages/openpyxl/worksheet/worksheet.py", line 392
    return f"{get_column_letter(min_col)}{min_row}:{get_column_letter(max_col)}{max_row}"
                                                                                        ^
SyntaxError: invalid syntax
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 1

Thank you very much in advance for your help.

**Comment by bluewww** [comment] 2020-01-27 23:35
duplicate of https://github.com/pulp-platform/pulp/issues/22

**Closed by bluewww** 2020-01-27 23:35 UTC
